import { expect, test } from "bun:test";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import type { LedgerRecord } from "../src/ledger/types";
import { stampBodyCheckErrors, stampDeliveryText } from "../src/stamp/cli";
import {
  buildDeliverySignature,
  renderDeliverySignature,
  renderDeliverySignatureStamped,
} from "../src/stamp/delivery-signature";
import {
  checkReviewStamps,
  compareVersionFixup,
  localIsoNow,
  readStampsMarker,
  recordReviewStampFromResult,
  STAMPS_MARKER_FILE,
} from "../src/stamp/record-review-stamp";
import {
  appendReviewStamp,
  computeTreeDigest,
  parseReviewStamp,
  REVIEW_STAMP_VERSION,
  renderReviewStamp,
} from "../src/stamp/review-stamp";
import {
  findingsReportLines,
  readVerdictFindings,
  VERDICT_FINDINGS_MAX_ISSUES,
  VERDICT_FINDINGS_REPORT_MAX_ISSUES,
} from "../src/stamp/verdict-findings";

const USAGE = {
  input: 500,
  output: 40,
  cacheRead: 1200,
  cacheWrite: 0,
  reasoning: 0,
  totalTokens: 1740,
  cost: { input: 0.01, output: 0.001, cacheRead: 0.002, cacheWrite: 0, total: 0.013 },
} as const;

function record(overrides: Partial<LedgerRecord> & { ts: number }): LedgerRecord {
  return {
    runId: "run-1",
    lane: "main",
    role: "coder",
    step: "turn:1",
    provider: "faux",
    model: "faux-1",
    stopReason: "toolUse",
    usage: { ...USAGE },
    ...overrides,
  };
}

test("the delivery signature carries tokens, cost, and per-role rows from ledger records", () => {
  const signature = buildDeliverySignature([
    record({ ts: 1, role: "coder", provider: "vendor", model: "big" }),
    record({ ts: 2, role: "coder", provider: "vendor", model: "big" }),
    record({ ts: 3, role: "reviewer", provider: "vendor", model: "small" }),
  ]);
  expect(signature.totalCalls).toBe(3);
  expect(signature.runIds).toEqual(["run-1"]);
  expect(signature.roles.find((row) => row.role === "reviewer")).toMatchObject({
    ran: true,
    calls: 1,
    provider: "vendor",
    model: "small",
  });
});

test("a role that never ran is named; a missing review never renders as a blank", () => {
  const text = renderDeliverySignature(buildDeliverySignature([record({ ts: 1 })]));
  expect(text).toContain("planner");
  expect(text).toContain("reviewer");
  expect((text.match(/did not run/g) ?? []).length).toBeGreaterThanOrEqual(2);
});

test("the rendered signature is compact: one header line plus one line per declared role", () => {
  const signature = buildDeliverySignature([record({ ts: 1 })]);
  const lines = renderDeliverySignature(signature).trimEnd().split("\n");
  expect(lines.length).toBe(1 + signature.roles.length);
});

test("the orchestrator lane is its own row: per-role calls and costs sum to the header", () => {
  const signature = buildDeliverySignature([
    record({ ts: 1, role: "orchestrator", provider: "vendor", model: "medium" }),
    record({ ts: 2, role: "orchestrator", provider: "vendor", model: "medium" }),
    record({ ts: 3, role: "planner", provider: "vendor", model: "big" }),
    record({ ts: 4, role: "coder", provider: "vendor", model: "small" }),
    record({ ts: 5, role: "reviewer", provider: "vendor", model: "small" }),
  ]);
  expect(signature.roles.find((row) => row.role === "orchestrator")).toMatchObject({
    ran: true,
    calls: 2,
    provider: "vendor",
    model: "medium",
  });
  const callsSum = signature.roles.reduce((sum, row) => sum + (row.calls ?? 0), 0);
  expect(callsSum).toBe(signature.totalCalls);
  const costSum = signature.roles.reduce((sum, row) => sum + (row.costUsd ?? 0), 0);
  expect(costSum).toBeCloseTo(signature.totalCostUsd, 10);
});

test("a run without orchestrator records still renders the orchestrator row as did not run", () => {
  const text = renderDeliverySignature(buildDeliverySignature([record({ ts: 1 })]));
  const orchestratorLine = text.split("\n").find((line) => line.startsWith("orchestrator"));
  expect(orchestratorLine).toBeDefined();
  expect(orchestratorLine).toContain("did not run");
});

test("the header names the count of unique runs and the totals (#435)", () => {
  const text = renderDeliverySignature(
    buildDeliverySignature([
      record({ ts: 1, runId: "run-a" }),
      record({ ts: 2, runId: "run-a" }),
      record({ ts: 3, runId: "run-b" }),
    ]),
  );
  const first = text.split("\n")[0] ?? "";
  expect(first.startsWith("runs=2 | calls=")).toBe(true);
  expect(first).toMatch(/cost=\$[0-9.]+ \| tokens fresh=[0-9]+ cached=[0-9]+ out=[0-9]+/);
  // 336: rows still lead with the orchestrator role and padEnd as before.
  expect(text.split("\n")[1]?.startsWith("orchestrator")).toBe(true);
});

const FORM_LEAD_IN =
  "Delivery signature, generated by ad-coder-dev (`ad-coder-dev stamp delivery` over this run's ledger):";

test("the published form is the lead-in, a blank line, and ONE fenced block (#435)", () => {
  const form = renderDeliverySignatureStamped(buildDeliverySignature([record({ ts: 1 })]));
  const lines = form.split("\n");
  expect(lines[0]).toBe(FORM_LEAD_IN);
  expect(lines[1]).toBe("");
  expect(lines[2]).toBe("```");
  expect(lines[3]?.startsWith("runs=")).toBe(true);
  expect(lines.at(-2)).toBe("```");
  const fences = lines.filter((line) => line === "```").length;
  expect(fences).toBe(2);
  // The report is exactly the bare rendering, unchanged inside the fence.
  const report = lines.slice(3, -2).join("\n");
  expect(`${report}\n`).toBe(renderDeliverySignature(buildDeliverySignature([record({ ts: 1 })])));
});

function gitRepo(): string {
  const root = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), "ad-coder-stamps-")));
  const git = (argv: string[]): void => {
    const child = Bun.spawnSync(["git", ...argv], { cwd: root, stdout: "pipe", stderr: "pipe" });
    if (child.exitCode !== 0) throw new Error(child.stderr.toString());
  };
  git(["init", "-q"]);
  git(["config", "user.email", "t@example.com"]);
  git(["config", "user.name", "t"]);
  return root;
}

function stampFixture() {
  return {
    treeDigest: "replace-me-digest",
    base: "main",
    verdict: "approved" as const,
    reviewer: "vendor/small",
    reviewedAt: "2026-09-20T10:00:00+02:00",
    runIds: ["run-1"],
    findingsRef: "docs/reviews/stamps.log",
  };
}

test("version fixup compares only branch paths and the narrow version definition", () => {
  const base = {
    "package.json": '{\n  "name": "ad-coder",\n  "version": "0.160.0"\n}\n',
    "CHANGELOG.md": "## [0.160.0] - 2026-09-20\n\n- reviewed\n",
  };
  const current = {
    ...base,
    "package.json": '{\n  "name": "ad-coder",\n  "version": "0.161.0"\n}\n',
    "CHANGELOG.md": "## [0.161.0] - 2026-09-20\n\n- reviewed\n",
  };
  expect(
    compareVersionFixup({
      reviewed: base,
      current,
      mainChangelog: base["CHANGELOG.md"],
      branchPaths: ["package.json", "CHANGELOG.md"],
      stampApproved: true,
      stampMatchesReviewed: true,
    }).ok,
  ).toBe(true);
  expect(
    compareVersionFixup({
      reviewed: base,
      current: { ...current, "src/code.ts": "changed\n" },
      mainChangelog: base["CHANGELOG.md"],
      branchPaths: ["package.json", "CHANGELOG.md", "src/code.ts"],
      stampApproved: true,
      stampMatchesReviewed: true,
    }).ok,
  ).toBe(false);
  expect(
    compareVersionFixup({
      reviewed: base,
      current: {
        ...current,
        "package.json": '{\n  "name": "changed",\n  "version": "0.161.0"\n}\n',
      },
      mainChangelog: base["CHANGELOG.md"],
      branchPaths: ["package.json", "CHANGELOG.md"],
      stampApproved: true,
      stampMatchesReviewed: true,
    }).ok,
  ).toBe(false);
});

test("version fixup permits the exact mechanical union of main changelog blocks", () => {
  const branch = "## [0.161.0] - 2026-09-20\n\n- branch\n";
  const main = "## [0.160.0] - 2026-09-19\n\n- main\n";
  expect(
    compareVersionFixup({
      reviewed: { "CHANGELOG.md": branch },
      current: { "CHANGELOG.md": `${branch}\n${main}` },
      mainChangelog: main,
      branchPaths: ["CHANGELOG.md"],
      stampApproved: true,
      stampMatchesReviewed: true,
    }).ok,
  ).toBe(true);
});

test("version fixup rejects an empty CI branch scope", () => {
  const result = compareVersionFixup({
    reviewed: { "src/code.ts": "old\n" },
    current: { "src/code.ts": "new\n" },
    mainChangelog: "",
    branchPaths: [],
    stampApproved: true,
    stampMatchesReviewed: true,
  });
  expect(result.ok).toBe(false);
});

test("version fixup rejects historical and unrelated changelog headings", () => {
  const reviewed =
    "## [0.161.0] - 2026-09-21\n\n- branch\n\n## [0.160.0] - 2026-09-20\n\n- historical\n";
  const main = "## [0.160.0] - 2026-09-20\n\n- historical\n";
  expect(
    compareVersionFixup({
      reviewed: { "CHANGELOG.md": reviewed },
      current: {
        "CHANGELOG.md": reviewed.replace("[0.160.0]", "[9.9.9]"),
      },
      mainChangelog: main,
      branchPaths: ["CHANGELOG.md"],
      stampApproved: true,
      stampMatchesReviewed: true,
    }).ok,
  ).toBe(false);
  expect(
    compareVersionFixup({
      reviewed: { "CHANGELOG.md": reviewed },
      current: { "CHANGELOG.md": `${reviewed}\n## [9.9.9] - 2026-09-22\n` },
      mainChangelog: main,
      branchPaths: ["CHANGELOG.md"],
      stampApproved: true,
      stampMatchesReviewed: true,
    }).ok,
  ).toBe(false);
});

test("a review stamp round-trips through render and parse", () => {
  const stamp = { ...stampFixture(), treeDigest: "a".repeat(64) };
  const rendered = renderReviewStamp(stamp);
  expect(rendered.startsWith(`${REVIEW_STAMP_VERSION} `)).toBe(true);
  expect(rendered.endsWith("\n")).toBe(true);
  expect(parseReviewStamp(rendered)).toEqual(stamp);
});

test("a stamp naming a digest no longer matching the tree is stale and must not pass", () => {
  const root = gitRepo();
  fs.writeFileSync(path.join(root, "f.txt"), "one\n");
  writeMarker(root, "stamps.log");
  addAll(root);
  const before = computeTreeDigest(root);
  expect(appendAndCheck(root, before).ok).toBe(true);

  // The cost of a stalled merge: the tree moved after the review -> stale.
  fs.writeFileSync(path.join(root, "f.txt"), "two\n");
  addAll(root);
  const after = computeTreeDigest(root);
  expect(after).not.toBe(before);
  // No new review, no new stamp: the old stamp must no longer pass.
  expect(checkReviewStamps(root).ok).toBe(false);
  expect(checkReviewStamps(root).failures[0]?.reason).toContain("stale");
});

function writeMarker(root: string, file: string): void {
  fs.writeFileSync(path.join(root, STAMPS_MARKER_FILE), JSON.stringify({ file }));
}

function addAll(root: string): void {
  const child = Bun.spawnSync(["git", "add", "-A"], { cwd: root, stdout: "pipe", stderr: "pipe" });
  if (child.exitCode !== 0) throw new Error(child.stderr.toString());
}

test("appending one more stamp line does not count as the tree moving", () => {
  const root = gitRepo();
  fs.writeFileSync(path.join(root, "f.txt"), "one\n");
  writeMarker(root, "stamps.log");
  addAll(root);
  const first = appendAndCheck(root, computeTreeDigest(root, ["stamps.log"]));
  expect(first.ok).toBe(true);
  appendAndCheck(root, computeTreeDigest(root, ["stamps.log"]));
  expect(checkReviewStamps(root).ok).toBe(true);
});

function appendAndCheck(root: string, digest: string): ReturnType<typeof checkReviewStamps> {
  appendReviewStamp(root, "stamps.log", { ...stampFixture(), treeDigest: digest });
  return checkReviewStamps(root);
}

test("a changes_requested verdict blocks the gate, and a fresh digest cannot excuse it", () => {
  const root = gitRepo();
  fs.writeFileSync(path.join(root, "f.txt"), "one\n");
  writeMarker(root, "stamps.log");
  const digest = computeTreeDigest(root);
  appendReviewStamp(root, "stamps.log", { ...stampFixture(), treeDigest: digest });
  fs.writeFileSync(path.join(root, "stamps.log"), ""); // isolate the second stamp
  appendReviewStamp(root, "stamps.log", {
    ...stampFixture(),
    treeDigest: digest,
    verdict: "changes_requested",
  });
  const verification = checkReviewStamps(root);
  expect(verification.ok).toBe(false);
  expect(verification.failures.map(({ reason }) => reason).join("\n")).toContain(
    "changes_requested",
  );
});

test("a malformed newest stamp fails the gate with the reason", () => {
  const root = gitRepo();
  fs.writeFileSync(path.join(root, "f.txt"), "one\n");
  fs.mkdirSync(path.join(root, "docs/reviews"), { recursive: true });
  fs.writeFileSync(path.join(root, "docs/reviews/stamps.log"), "garbage\n");
  expect(checkReviewStamps(root).ok).toBe(false);
});

test("the marker file opt-in: absent means off everywhere, malformed means blocked", () => {
  const root = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), "ad-coder-stamps-off-")));
  expect(readStampsMarker(root)).toBeUndefined();
  const result = recordReviewStampFromResult(root, settledResult());
  expect(result.recorded).toBe(false);
  expect(result.skippedBecause).toContain("not a stamp-writing repository");

  fs.writeFileSync(path.join(root, STAMPS_MARKER_FILE), "not json");
  expect(() => readStampsMarker(root)).toThrow(STAMPS_MARKER_FILE);
});

test("the settle hook stamps an approved run and refuses to certify a review-less run", () => {
  const withMarker = gitRepo();
  fs.writeFileSync(
    path.join(withMarker, STAMPS_MARKER_FILE),
    JSON.stringify({ file: "docs/reviews/stamps.log" }),
  );
  const recorded = recordReviewStampFromResult(withMarker, settledResult());
  expect(recorded.recorded).toBe(true);
  const text = fs.readFileSync(path.join(withMarker, "docs/reviews/stamps.log"), "utf8");
  const parsed = parseReviewStamp(text.trimEnd().split("\n").at(-1) ?? "");
  if (typeof parsed === "string") throw new Error(parsed);
  expect(parsed.verdict).toBe("approved");
  expect(parsed.treeDigest).toBe(computeTreeDigest(withMarker));
  expect(parsed.reviewer).toMatch(/faux\/model/);

  const reviewless = gitRepo();
  fs.writeFileSync(path.join(reviewless, STAMPS_MARKER_FILE), JSON.stringify({}));
  const skipped = recordReviewStampFromResult(reviewless, {
    ...settledResult(),
    reviewRan: false,
  });
  expect(skipped.recorded).toBe(false);
  expect(skipped.skippedBecause).toContain("without a review round");
});

test("body-check passes when the body carries the freshly rendered delivery block", () => {
  const dir = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), "ad-coder-body-check-")));
  try {
    const ledger = path.join(dir, "ledger.jsonl");
    fs.writeFileSync(
      ledger,
      `${JSON.stringify(record({ ts: 1, role: "coder", provider: "vendor", model: "big" }))}\n` +
        `${JSON.stringify(record({ ts: 2, role: "reviewer", provider: "vendor", model: "small" }))}\n`,
    );
    const body = path.join(dir, "body.md");
    const form = stampDeliveryText(dir, [ledger]);
    fs.writeFileSync(body, `## Delivery\n\nSome prose around it.\n\n${form}End.\n`);
    expect(stampBodyCheckErrors(body, dir, [ledger])).toEqual([]);
    // One trailing-newline difference around the form is tolerated.
    fs.writeFileSync(body, `pre\n${form.trimEnd()}\npost\n`);
    expect(stampBodyCheckErrors(body, dir, [ledger])).toEqual([]);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test("body-check fails with the absent error when the body carries no block", () => {
  const dir = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), "ad-coder-body-absent-")));
  try {
    const ledger = path.join(dir, "ledger.jsonl");
    fs.writeFileSync(ledger, `${JSON.stringify(record({ ts: 1 }))}\n`);
    const body = path.join(dir, "body.md");
    fs.writeFileSync(body, "## Delivery\n\nNo cost block here at all.\n");
    const failures = stampBodyCheckErrors(body, dir, [ledger]);
    expect(failures.length).toBe(1);
    expect(failures[0]?.reason).toContain("the generated delivery form is absent");
    expect(failures[0]?.reason).toContain(body);
    expect(failures[0]?.action).toContain("ad-coder stamp delivery");
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test("body-check fails with the stale error when the body block differs from the ledger", () => {
  const dir = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), "ad-coder-body-stale-")));
  try {
    const ledger = path.join(dir, "ledger.jsonl");
    fs.writeFileSync(ledger, `${JSON.stringify(record({ ts: 1 }))}\n`);
    const body = path.join(dir, "body.md");
    // A form-shaped stale paste: the prose lead-in plus a fenced `runs=`-headed
    // block whose totals no longer match the ledger -- the classic stale paste
    // after more ledger lines landed.
    fs.writeFileSync(
      body,
      "Delivery signature, generated by ad-coder-dev (`ad-coder-dev stamp delivery` over this run's ledger):\n\n" +
        "```\n" +
        "runs=1 | calls=99 | cost=$999.000000 | tokens fresh=0 cached=0 out=0\n" +
        "coder     vendor/small                     calls=1   cost=$0.010000\n" +
        "```\n",
    );
    const failures = stampBodyCheckErrors(body, dir, [ledger]);
    expect(failures.length).toBe(1);
    expect(failures[0]?.reason).toContain("the delivery block is stale");
    expect(failures[0]?.reason).toContain("prose lead-in with a fenced runs= block");
    expect(failures[0]?.action).toContain("ad-coder stamp delivery");
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test("the gate's similar-block rule is whitespace-tolerant over the new first line", () => {
  const dir = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), "ad-coder-body-similar-")));
  try {
    const ledger = path.join(dir, "ledger.jsonl");
    fs.writeFileSync(ledger, `${JSON.stringify(record({ ts: 1 }))}\n`);
    const body = path.join(dir, "body.md");
    // Indented `runs=` line and the lead-in pasted with the trailing colon --
    // neither equals the fresh rendering, both must read as stale, not absent.
    fs.writeFileSync(
      body,
      `${FORM_LEAD_IN}\n\n  runs=1 | calls=99 | cost=$999.000000 | tokens fresh=0 cached=0 out=0\n`,
    );
    const failures = stampBodyCheckErrors(body, dir, [ledger]);
    expect(failures.length).toBe(1);
    expect(failures[0]?.reason).toContain("the delivery block is stale");
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

function settledResult() {
  return {
    outcome: "approved",
    approved: true,
    rounds: 1,
    verdicts: [{ status: "approved", issues: [], summary: "ok" }],
    runIds: ["run-a", "run-b"],
    stageMetrics: [
      {
        stage: "review:1",
        provider: "faux",
        model: "model",
        input: 0,
        cachedInput: 0,
        freshInput: 0,
        output: 0,
        requestBytes: { systemPrompt: 0, prompt: 0, toolDefinitions: 0, total: 0 },
        readFiles: [],
        readFilesTotal: 0,
        readFilesTruncated: 0,
        diffBytes: 0,
      },
    ],
    reviewRan: true,
  } as unknown as import("../src/orchestration/types").PipelineResult;
}

test("reviewedAt is ISO-8601 with the machine's own local offset", () => {
  const iso = localIsoNow(new Date(2026, 8, 20, 10, 0));
  expect(iso).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[+-]\d{2}:\d{2}$/);
});

test("a malformed stamp line is a parse error, never a throw", () => {
  expect(typeof parseReviewStamp("")).toBe("string");
  expect(typeof parseReviewStamp("random text")).toBe("string");
  expect(typeof parseReviewStamp(`${REVIEW_STAMP_VERSION} digest:${"a".repeat(64)}`)).toBe(
    "string",
  );
});

test("a standalone reviewer run stamps through the same writer as the pipeline", () => {
  // The stamp never needed a pipeline -- only a review that produced a
  // structured verdict (issue #283). Before this, `role reviewer` could return a
  // real verdict and had no way to record it: the gate demanded paperwork the
  // cheap path could not produce, which teaches stepping around the gate.
  const root = gitRepo();
  fs.writeFileSync(path.join(root, STAMPS_MARKER_FILE), JSON.stringify({}));
  const recorded = recordReviewStampFromResult(root, {
    approved: false,
    runIds: ["standalone-run"],
    stageMetrics: [{ stage: "review:1", provider: "opencode-go", model: "glm-5.3-flash" }],
    reviewRan: true,
  });
  expect(recorded.recorded).toBe(true);
  const line = fs
    .readFileSync(path.join(root, "docs/reviews/stamps.log"), "utf8")
    .trimEnd()
    .split("\n")
    .at(-1);
  const parsed = parseReviewStamp(line ?? "");
  if (typeof parsed === "string") throw new Error(parsed);
  // `changes_requested` stamps too: "the reviewer said no" is a fact the gate
  // should read, not re-derive from prose.
  expect(parsed.verdict).toBe("changes_requested");
  expect(parsed.reviewer).toBe("opencode-go/glm-5.3-flash");
  expect(parsed.runIds).toEqual(["standalone-run"]);
});

test("a changes_requested settle persists the findings as the run artifact, and the stamp ref names it", () => {
  // The loss issue #466 fixes: a blocking verdict whose issues existed only in
  // the settle's live objects and the transcript. The artifact must be ON DISK
  // in the store's durable layout, with the verdict's own issues, before any
  // stamp gating decides whether target paperwork happens.
  const root = gitRepo();
  fs.writeFileSync(path.join(root, STAMPS_MARKER_FILE), JSON.stringify({ file: "stamps.log" }));
  const result = recordReviewStampFromResult(root, {
    approved: false,
    runIds: ["run-a", "run-review"],
    stageMetrics: [{ stage: "review:1", provider: "opencode-go", model: "glm-5.3-flash" }],
    reviewRan: true,
    verdicts: [
      { status: "approved", issues: [], summary: "first round looked fine" },
      {
        status: "changes_requested",
        issues: [
          { severity: "blocker", what: "the gate acceptor is untested" },
          { severity: "major", what: "the migration help lies about the default" },
        ],
        summary: "two real findings; the rest is style",
      },
    ],
  });
  // The outcome carries the ref the settle derived, not a recomputation.
  expect(result.findingsRef).toBe(".ad-coder/runs/verdict-run-review.json");
  // The artifact's OWN content is asserted -- the file on disk, not a rendering.
  const value = readVerdictFindings(root, "run-review");
  expect(value.verdict).toBe("changes_requested");
  expect(value.runId).toBe("run-review");
  expect(value.summary).toBe("two real findings; the rest is style");
  expect(value.issues).toEqual([
    { severity: "blocker", what: "the gate acceptor is untested" },
    { severity: "major", what: "the migration help lies about the default" },
  ]);
  expect(value.issueCount).toBe(2);
  expect(value.issuesTruncated).toBe(false);
  expect(value.schemaVersion).toBe(1);
  expect(value.writtenAt).toBeTruthy();
  // And the artifact was written BEFORE the stamp gating: it survives even a
  // stamp the target does not want.
  const noMarker = gitRepo();
  const notStamped = recordReviewStampFromResult(noMarker, {
    approved: false,
    runIds: ["run-only"],
    stageMetrics: [{ stage: "review:1", provider: "faux", model: "m" }],
    reviewRan: true,
    verdicts: [
      {
        status: "changes_requested",
        issues: [{ severity: "major", what: "the wording lies" }],
        summary: "one finding",
      },
    ],
  });
  expect(notStamped.recorded).toBe(false); // no marker -> no stamp
  expect(notStamped.findingsRef).toBe(".ad-coder/runs/verdict-run-only.json");
  expect(readVerdictFindings(noMarker, "run-only").issues).toEqual([
    { severity: "major", what: "the wording lies" },
  ]);
});

test("the findings ref is the artifact for changes_requested and '-' for approved", () => {
  const root = gitRepo();
  fs.writeFileSync(path.join(root, STAMPS_MARKER_FILE), JSON.stringify({ file: "stamps.log" }));
  // Approved with no findings: '-' everywhere, and nothing is written.
  const approved = recordReviewStampFromResult(root, settledResult());
  expect(approved.recorded).toBe(true);
  expect(approved.findingsRef).toBe("-");
  expect(fs.existsSync(path.join(root, ".ad-coder/runs/verdict-run-b.json"))).toBe(false);
  // And the stamp line itself carries the ref, never the stamps log it lives in.
  const stampLine = fs
    .readFileSync(path.join(root, "stamps.log"), "utf8")
    .trimEnd()
    .split("\n")
    .at(-1);
  const parsed = parseReviewStamp(stampLine ?? "");
  if (typeof parsed === "string") throw new Error(parsed);
  expect(parsed.findingsRef).toBe("-");
  // findingsRef on the stamp line names the artifact when the verdict
  // disapproved.
  fs.rmSync(path.join(root, "stamps.log"));
  const blocked = recordReviewStampFromResult(root, {
    ...settledResult(),
    approved: false,
    verdicts: [
      {
        status: "changes_requested",
        issues: [{ severity: "major", what: "the wording lies" }],
        summary: "one finding",
      },
    ],
  });
  expect(blocked.findingsRef).toBe(".ad-coder/runs/verdict-run-b.json");
  const blockedLine = fs
    .readFileSync(path.join(root, "stamps.log"), "utf8")
    .trimEnd()
    .split("\n")
    .at(-1);
  const blockedParsed = parseReviewStamp(blockedLine ?? "");
  if (typeof blockedParsed === "string") throw new Error(blockedParsed);
  expect(blockedParsed.verdict).toBe("changes_requested");
  expect(blockedParsed.findingsRef).toBe(".ad-coder/runs/verdict-run-b.json");
});

test("the settle report is bounded in lines and length, and says plainly when it truncates", () => {
  // Issue #463 is the reader side of this class; HERE the writer's stderr
  // report must shade in the findings beside the count line, but never without
  // bound: a verbose reviewer cannot write an unbounded stderr through it.
  const little = findingsReportLines(".ad-coder/runs/verdict-r.json", [
    { severity: "major", what: "the gate acceptor is untested" },
  ]);
  expect(little[0]).toBe("findings .ad-coder/runs/verdict-r.json");
  expect(little).toEqual([
    "findings .ad-coder/runs/verdict-r.json",
    "1. major: the gate acceptor is untested",
  ]);
  // Long text is clipped per line WITH the clip named.
  const clipped = findingsReportLines("ref", [{ severity: "minor", what: "x".repeat(500) }]);
  expect(clipped).toHaveLength(2);
  expect(clipped[1]).toBe(`1. minor: ${"x".repeat(200)}…[report line clipped]`);
  // More issues than the report shades in: the truncation is SAID, with the
  // pointer to where the full findings are.
  const many = Array.from({ length: VERDICT_FINDINGS_MAX_ISSUES * 2 }, (_, index) => ({
    severity: "major",
    what: `finding ${index + 1}`,
  }));
  const truncated = findingsReportLines("ref", many);
  expect(truncated).toHaveLength(1 + VERDICT_FINDINGS_REPORT_MAX_ISSUES + 1);
  expect(truncated.at(-1)).toContain("report truncated");
  expect(truncated.at(-1)).toContain(String(many.length));
  expect(truncated.at(-1)).toContain("in ref");
});
